# docker-compose.yml

version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app  # Optional for development
    environment:
      - ENV=production

  ui:
    build:
      context: ./ui
    container_name: ui
    ports:
      - "7860:7860"
    depends_on:
      - backend
    volumes:
      - ./ui:/app  # Optional for development

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # Expose Qdrant's API
