name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Docker Compose
      run: |
        docker-compose version || sudo apt-get update && sudo apt-get install docker-compose

    - name: Build and Start Containers
      run: |
        docker-compose up --build -d

    - name: Verify Containers
      run: |
        docker-compose ps

    - name: Stop and Remove Containers
      if: always()
      run: |
        docker-compose down
