
name: Docker Compose CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:




    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      
    - name: Build and Start Containers
      working-directory: ./project # Adjust this path to the directory containing docker-compose.yml
      run: docker-compose up --build -d
    
    - name: Verify Containers
      working-directory: ./project
      run: docker-compose ps

    - name: Stop and Remove Containers
      if: always()
      working-directory: ./project
      run: docker-compose down
